const awardsList = [
  "Academy Award",
  "Golden Globe Award",
  "BAFTA Award",
  "Screen Actors Guild Award",
  "Critics' Choice Movie Award",
  "Directors Guild of America Award",
  "Producers Guild of America Award",
  "Writers Guild of America Award",
  "Cannes Film Festival Palme d'Or",
  "Venice Film Festival Golden Lion",
  "Berlin International Film Festival Golden Bear",
  "Sundance Film Festival Grand Jury Prize",
  "Toronto International Film Festival People's Choice Award",
  "MTV Movie & TV Awards",
  "National Board of Review Award",
  "New York Film Critics Circle Award",
  "Los Angeles Film Critics Association Award",
  "American Film Institute Award",
  "Satellite Award",
  "Independent Spirit Award",
  "Hollywood Film Award",
  "Gotham Independent Film Award",
  "National Society of Film Critics Award",
  "British Independent Film Award",
  "European Film Award",
  "César Award",
  "Goya Award",
  "Filmfare Award",
  "Asia Pacific Screen Award",
  "African Movie Academy Award",
  "Annie Award",
  "Daytime Emmy Award",
  "Primetime Emmy Award",
  "Genie Award",
  "Golden Raspberry Award",
  "Grammy Award",
  "Kids' Choice Award",
  "Nickelodeon Kids' Choice Award",
  "People's Choice Award",
  "Teen Choice Award",
  "Tony Award",
  " turn Award",
  "Hugo Award",
  "Nebula Award",
  "Bram Stoker Award",
  "Edgar Allan Poe Award",
  "Golden Horse Award (Taiwan)",
  "Blue Ribbon Award (Japan)",
  "Mainichi Film Award (Japan)",
  "Kinema Junpo Award (Japan)",
  "Japan Academy Prize",
  "Grand Bell Award (South Korea)",
  "Blue Dragon Film Award (South Korea)",
  "Ariel Award (Mexico)",
  "Golden Lotus Award (India)",
  "Nika Award (Russia)",
  "Golden Rooster Award (China)",
  "Hong Kong Film Award",
  "Golden Bauhinia Award (Hong Kong)",
  "Saturn Award",
];

export default awardsList;
