const genresList = [
  "Action",
  "Adventure",
  "Animation",
  "Biography",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "Film Noir",
  "History",
  "Horror",
  "Music",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Short Film",
  "Sport",
  "Superhero",
  "Thriller",
  "War",
  "Western",
  "Zombie",
  "Cyberpunk",
  "Psychological Thriller",
  "Fantasy Adventure",
  "Historical Fiction",
  "Satire",
  "Musical Comedy ",
  " Film Noir",
  "Psychological Horror",
  "Historical Drama",
  "Science Fantasy",
  "Dark Comedy",
  "Cyberpunk",
  "Neo-Noir",
  "Space Opera",
  "Surreal",
  "Steampunk",
  "Magical Realism",
];

export default genresList;
